spring:
  batch:
    task.execution.pool:
      core-size: 3
      max-size: 5
      queue-capacity: 500
    job:
      name: ${BATCH_JOB_NAME:batch}
      chunk-size: 100
---
spring:
  config.activate.on-profile: test
  h2.console.enabled: true
  datasource:
    meta:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:batch;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: admin
    outbox:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:outbox;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: admin
---
spring:
  config.activate.on-profile: local
  datasource:
    meta:
      driver-class-name: ${BATCH_DB_DRIVER}
      jdbc-url: jdbc:mysql://${BATCH_DB_URL}
      username: ${BATCH_DB_USERNAME}
      password: ${BATCH_DB_PASSWORD}
