spring:
  datasource:
    meta:
      driver-class-name: ${BATCH_DB_DRIVER}
      jdbc-url: jdbc:mysql://${BATCH_DB_URL}
      username: ${BATCH_DB_USERNAME}
      password: ${BATCH_DB_PASSWORD}
  batch:
    job.name: ${BATCH_JOB_NAME}
    chunk-size: 100
    task.execution.pool:
      core-size: 3
      max-size: 5
      queue-capacity: 500

