version: '3.8'
services:
  aws:
    image: "localstack/localstack"
    container_name: "localstack"
    env_file: "localstack.env"
    command: "chmod +x /etc/localstack/init/ready.d/init-aws.sh"
    volumes:
      - "./localstack.sh:/etc/localstack/init/ready.d/init-aws.sh"
    ports:
      - "4566:4566"