version: '3.8'
services:
  aws:
    image: "localstack/localstack"
    container_name: "localstack"
    env_file: "${LOCALSTACK_VOLUME_BASE}/localstack.env"
    command: "chmod +x /etc/localstack/init/ready.d/init-aws.sh"
    volumes:
      - "./localstack.sh:/etc/localstack/init/ready.d/init-aws.sh"
    ports:
      - "${LOCALSTACK_PORT}:${LOCALSTACK_PORT}"
  rdb-1:
    image: "${RDB_IMAGE}"
    container_name: "command"
    env_file: "${COMMAND_VOLUME_BASE}/rdb-command.env"
    command: "${RDB_OPTION}"
    ports:
      - "${COMMAND_DB_PORT}:3306"
    volumes:
      - "${COMMAND_VOLUME_BASE}/rdb-command-init.sql:/docker-entrypoint-initdb.d/init-rdb.sql"
  rdb-2:
    image: "${RDB_IMAGE}"
    container_name: "outbox"
    env_file: "${OUTBOX_VOLUME_BASE}/rdb-outbox.env"
    command: "${RDB_OPTION}"
    ports:
      - "${OUTBOX_DB_PORT}:3306"
    volumes:
      - "${OUTBOX_VOLUME_BASE}/rdb-outbox-init.sql:/docker-entrypoint-initdb.d/init-rdb.sql"
  rdb-3:
    image: "${RDB_IMAGE}"
    container_name: "batch"
    env_file: "${BATCH_VOLUME_BASE}/rdb-batch.env"
    command: "${RDB_OPTION}"
    ports:
      - "${BATCH_DB_PORT}:3306"
    volumes:
      - "${BATCH_VOLUME_BASE}/rdb-batch-init.sql:/docker-entrypoint-initdb.d/init-rdb.sql"