version: '3.8'
services:
  example-localstack:
    image: localstack/localstack
    container_name: example-localstack
    env_file: ./volumes/localstack/localstack.env
    command: chmod +x /etc/localstack/init/ready.d/init-aws.sh
    volumes:
      - ./localstack.sh:/etc/localstack/init/ready.d/init-aws.sh
    ports:
      - "4566:4566"
  example-command-db:
    image: mysql:8.4.3
    container_name: example-command-db
    env_file: ./volumes/command/command.env
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/command/command-init.sql:/docker-entrypoint-initdb.d/init-rdb.sql
  example-outbox-batch-db:
    image: mysql:8.4.3
    container_name: example-outbox-batch-db
    env_file: ./volumes/batch/batch.env
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3307:3306"
    volumes:
      - ./volumes/batch/batch-init.sql:/docker-entrypoint-initdb.d/init-rdb.sql
  example-query-db:
    image: mongo
    container_name: example-query-db
    env_file: ./volumes/query/query.env
    ports:
      - "27017:27017"
    volumes:
      - ./volumes/query/query-init.js:/docker-entrypoint-initdb.d/init-db.js
  example-redis:
    image: redis:latest
    container_name: example-redis
    command: redis-server /usr/local/conf/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/redis/data:/data
      - ./volumes/redis/redis.conf:/usr/local/conf/redis.conf
    labels:
      - "name=redis"
      - "mode=standalone"
  example-command-server:
    build:
      context: ./example-command
      args:
        SERVER_PATH: module-api
        SERVER_PORT: 8080
        SERVER_PROFILE: local
    container_name: example-command-serve
    env_file: ./volumes/command.env
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4g
    depends_on:
      - example-localstack
      - example-command-db
      - example-redis
  example-query-server:
    build:
      context: ./example-query
      args:
        SERVER_PATH: module-api
        SERVER_PORT: 8080
        SERVER_PROFILE: local
    container_name: example-query-server
    env_file: ./volumes/query.env
    ports:
      - "8090:8080"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4g
    depends_on:
      - example-localstack
      - example-query-db