version: '3.8'
services:
  aws:
    image: "localstack/localstack"
    container_name: "localstack"
    env_file: "${SQS_VOLUME_BASE}/localstack.env"
    command: "chmod +x /etc/localstack/init/ready.d/init-aws.sh"
    volumes:
      - "${SQS_VOLUME_BASE}/localstack.sh:/etc/localstack/init/ready.d/init-aws.sh"
    ports:
      - "${SQS_PORT}:${SQS_PORT}"