rootProject.name = 'spring-boot-example'

// Bounded Contexts - Acquisition
include 'modules:bounded-context:acquisition-api'
include 'modules:bounded-context:acquisition-application'
include 'modules:bounded-context:acquisition-domain'
include 'modules:bounded-context:acquisition-infra'

// Bounded Contexts - Derivation
include 'modules:bounded-context:derivation-api'
include 'modules:bounded-context:derivation-application'
include 'modules:bounded-context:derivation-domain'
include 'modules:bounded-context:derivation-infra'

// Common Modules
include 'modules:common:app'
include 'modules:common:contract'
include 'modules:common:core'
include 'modules:common:infrastructure'
