spring:
  application.name: application-api
  profiles.active: local
  web.resources.add-mappings: false
  config:
    import:
      - batch.yml
      - api-client.yml
      - db-command.yml
      - db-event.yml
      - event-sns.yml
      - sqs-pub.yml
  task.execution.pool:
    core-size: 10
    max-size: 10
    queue-capacity: 1000
server:
  tomcat:
    threads:
      max: 200
      min-spare: 100
    max-connections: 10000
    accept-count: 100
    connection-timeout: 20000
  port: 8080

logging:
  level:
    org.springframework.boot.autoconfigure: warn

---
spring.config.activate.on-profile: test

---
spring.config.activate.on-profile: local