spring:
  application.name: boot
  profiles.active: local
  web.resources.add-mappings: false

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_batch_fetch_size: 100

---
spring.config:
  activate.on-profile: test
  import:
    - classpath:db/h2.yml

---
spring.config:
  activate.on-profile: local
  import:
    - classpath:db/local.yml
env:
  db:
    mysql:
      url: ${ENV_DB_MYSQL_URL}
      username: ${ENV_DB_MYSQL_USERNAME}
      password: ${ENV_DB_MYSQL_PASSWORD}