---
spring:
  config.activate.on-profile: test
  
---
spring:
  config.activate.on-profile: local
  data:
    mongodb:
      database: query
      uri: ${QUERY_DB_URI}
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy