spring:
  jpa:
    hibernate.ddl-auto: create
    properties:
      hibernate:
        highlight_sql: true
        show_sql: true
  h2.console.enabled: true
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:local;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: admin
      pool-name: hikari-db-pool
