spring:
  cloud:
    aws:
      stack.auto: false
      end-point.url: ${MESSAGE_ENDPOINT_URL}
      region.static: ${MESSAGE_DEFAULT_REGION}
      credentials:
        access-key: ${MESSAGE_ACCESS_KEY_ID}
        secret-key: ${MESSAGE_SECRET_ACCESS_KEY}
      sqs:
        queue.name:
          team-create: ${TEAM_CREATE_QUEUE_NAME}