version: '3.8'
services:
  batch:
    image: ${RDB_IMAGE}
    container_name: batch
    env_file: ${BATCH_VOLUME_BASE}/batch.env
    command: ${RDB_OPTION}
    ports:
      - ${BATCH_DB_PORT}:3306
    volumes:
      - ${BATCH_VOLUME_BASE}/batch-init.sql:/docker-entrypoint-initdb.d/init-rdb.sql
