spring:
  cloud:
    aws:
      stack.auto: false
      sqs:
        end-point: ${MESSAGE_ENDPOINT_URL}
        region: ${MESSAGE_DEFAULT_REGION}
        access-key: ${MESSAGE_ACCESS_KEY_ID}
        secret-key: ${MESSAGE_SECRET_ACCESS_KEY}
        queue:
          team: ${MESSAGE_TEAM_QUEUE}
          player: ${MESSAGE_PLAYER_QUEUE}
          delete-team: ${MESSAGE_DELETE_TEAM_QUEUE}
      sns:
        topic-arn: ${TEAM_TOPIC_ARN}
        region: ${MESSAGE_DEFAULT_REGION}
        access-key: ${MESSAGE_ACCESS_KEY_ID}
        secret-key: ${MESSAGE_SECRET_ACCESS_KEY}
        type-key: ${MESSAGE_TYPE_KEY}
