spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_batch_fetch_size: 100

---
spring:
  config.activate.on-profile: test
  jpa:
    hibernate.ddl-auto: create
    properties:
      hibernate:
        highlight_sql: true
        show_sql: true
  h2.console.enabled: true
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:local;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: admin
      pool-name: hikari-db-pool

---
spring:
  config.activate.on-profile: local
  jpa.properties.hibernate:
    show_log: true
    highlight_sql: true
    show_sql: true
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://${ENV_DB_MYSQL_URL}
      username: ${ENV_DB_MYSQL_USERNAME}
      password: ${ENV_DB_MYSQL_PASSWORD}
      pool-name: hikari-db-pool
      maximum-pool-size: 5
      validation-timeout: 1000
      connection-timeout: 1500
      keepalive-time: 30000
      max-lifetime: 300000
      data-source-properties:
        cachePrepStmts: true
        useServerPrepStmts: true
        prepStmtCacheSize: 300
        prepStmtCacheSqlLimit: 2048
        socketTimeout: 3000
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
        rewriteBatchedStatements: true