spring:
  jpa:
    open-in-view: false
    hibernate.ddl-auto: none
    properties.hibernate.default_batch_fetch_size: 100

---
spring:
  config.activate.on-profile: test
  jpa:
    hibernate.ddl-auto: create
    properties:
      hibernate:
        highlight_sql: true
        show_sql: true
  h2.console.enabled: true
  datasource:
    command:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:command;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: admin
      pool-name: hikari-command-pool
    outbox:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:outbox;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: admin
      pool-name: hikari-outbox-pool

---
spring:
  config.activate.on-profile: local
  jpa:
    properties.hibernate:
      show_log: true
      highlight_sql: true
      show_sql: true
  datasource:
    command:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://${COMMAND_DB_URL}
      username: ${COMMAND_DB_USERNAME}
      password: ${COMMAND_DB_PASSWORD}
      pool-name: hikari-command-pool
      maximum-pool-size: 5
      validation-timeout: 1000
      connection-timeout: 1500
      keepalive-time: 30000
      max-lifetime: 300000
      data-source-properties:
        cachePrepStmts: true
        useServerPrepStmts: true
        prepStmtCacheSize: 300
        prepStmtCacheSqlLimit: 2048
        socketTimeout: 3000
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
        rewriteBatchedStatements: true
    outbox:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://${OUTBOX_DB_URL}
      username: ${OUTBOX_DB_USERNAME}
      password: ${OUTBOX_DB_PASSWORD}
      pool-name: hikari-outbox-pool