spring:
  cloud:
    aws:
      sns:
        topic-arn: ${TEAM_TOPIC_ARN}
        region: ${MESSAGE_DEFAULT_REGION}
        access-key: ${MESSAGE_ACCESS_KEY_ID}
        secret-key: ${MESSAGE_SECRET_ACCESS_KEY}
        type-key: ${MESSAGE_TYPE_KEY}
