---
spring:
  config.activate.on-profile: test
  datasource:
    inbox:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:inbox;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: admin
      pool-name: hikari-inbox-pool
    outbox:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:outbox;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: admin
      pool-name: hikari-outbox-pool


---
spring:
  config.activate.on-profile: local
  datasource:
    inbox:
      driver-class-name: ${INBOX_DB_DRIVER}
      jdbc-url: jdbc:mysql://${INBOX_DB_URL}
      username: ${INBOX_DB_USERNAME}
      password: ${INBOX_DB_PASSWORD}
      pool-name: hikari-inbox-pool
    outbox:
      driver-class-name: ${OUTBOX_DB_DRIVER}
      jdbc-url: jdbc:mysql://${OUTBOX_DB_URL}
      username: ${OUTBOX_DB_USERNAME}
      password: ${OUTBOX_DB_PASSWORD}
      pool-name: hikari-outbox-pool